baseURL : /
languageCode : en-us
title : Hack3 - Experience Innovation
theme : sodium-theme

taxonomies:
  category: categories
  tag: tags

params:
  social:
    facebook: uicardio
    instagram: uicardio
    twitter: uicardio

  scripts:
    googleanalytics: 
    disqus: 
    
